### ISSUE TITLE
I'd like to have a function call back for updating progress

### ISSUE THREAD

**Issue by DoctorLai** [I3ck/cppOpt#7] opened 2017-04-06 13:49 UTC
For example, I'd like to pass a function pointer to the cppOpt so that I can let users know the progress if the optimisation takes time.

**Comment by I3ck** [comment] 2017-04-06 17:47
I think you should be able to do so by putting such logic into your calculate method. Since this is called with every step.

**Comment by DoctorLai** [comment] 2017-04-06 21:04
My understanding is that the calculate method is the  cost function.  Taken Simulated Annealing for example, the caller does not know how many iterations have been completed.

**Comment by I3ck** [comment] 2017-04-07 15:26
Each call to calculate would be one iteration. So you could simply increment a counter within the method. You could write a `MySolverWithProgressLogging`

**Comment by I3ck** [comment] 2017-04-10 16:32
Can you resolve the issue this way?

**Comment by I3ck** [comment] 2017-04-11 16:40
I'll close this for now, feel free to reopen it, if you still need help

**Comment by DoctorLai** [comment] 2017-04-13 13:52
Hi, thanks for the info.
However, wouldn't it be more logical that a method is provided to return the progress?
A counter can be placed inside the calculate, but that value needs to be divided by the total number of iterations, which again needs to be exposed somewhere, but still not so straightforward.

**Comment by I3ck** [comment] 2017-04-14 11:44
The issue is that the more logic I add, the more expensive the optimization gets. I had some thoughts about changing the lib in the future and I'd like to make it even more lightweight.  
Some users might optimize problems where each calculation takes > 100ms or even seconds / minutes. There these overheads aren't really an issue.  
But with fast calculations, which are e.g. presented within the examples, the overhead of the optimization can get very severe.  
I think adding e.g. `MySolverWithProgressLogging` or similar extended base calculators might help here.  
The library users could choose the fastest optimization or plug some of the more informative / useful calculators in.

**Comment by I3ck** [comment] 2017-04-14 11:45
I'll reopen this issue as reference for future changes to the library. But for now I'd suggest extending the calculate method to one's needs

**Comment by I3ck** [comment] 2017-11-03 08:56
I now refactored the library, and still think it's best to extend the calculation function to track the progress. See the example with [logging added to the calculate function](../blob/master/examples/example_simulated_annealing_x_square_logging.cpp). Tracking the progress can be done in a similar way.

**Closed as completed by I3ck** 2017-11-03 08:56 UTC
